name: build
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs-version: [
          '27.2', '28.2', '29.1', '29.2', '29.3', '30.1', 'snapshot'
        ]
        action: ['check', 'lint']

      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}
      - name: Run ${{ matrix.action }}
        run: |
          make ${{ matrix.action }}
